name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout - Descargar tu código
    - name: Checkout code
      uses: actions/checkout@v4
    
    # 2. Docker set up buildx - Configurar Docker para builds avanzados
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # 3. Docker login - Autenticarse en Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # 4. Docker Build and push - Construir y subir imagen
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/rick-morty-app:latest